name: Run tests

on:
  workflow_dispatch:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  tests:
    name: Run tests
    runs-on: [macos-12]
    timeout-minutes: 90
    env:
      DEVELOPER_DIR: /Applications/Xcode_14.2.app/Contents/Developer

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2.4.2

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Run Android Tests
        run:  ./gradlew shared:testReleaseUnitTest

      - name: Run iOS Tests
        run:  ./gradlew shared:iosX64Test

      - if: github.event_name == 'pull_request'
        name: Create code coverage
        run:  ./gradlew shared:koverXmlReport

      - if: github.event_name == 'pull_request'
        name: Add coverage report to PR
        id: kover
        uses: mi-kas/kover-report@v1
        with:
          path: ${{ github.workspace }}/shared/build/reports/kover/xml/report.xml
          token: ${{ secrets.GITHUB_TOKEN }}
          title: Code Coverage
          update-comment: true
          min-coverage-overall: 80
          min-coverage-changed-files: 80
          coverage-counter-type: LINE
